import {postAction,getAction, deleteAction,putAction} from "./manage";


export const adminGetFood=(params)=>getAction("/api/admin/food",params)
export const adminTop=(params)=>postAction("/api/admin/food/top",params)
export const adminNotTop=(params)=>postAction("/api/admin/food/untop",params)
export const adminGetAlerts=(params)=>getAction("/api/admin/announcement",params)
export const adminDeleteAlerts=(params)=>deleteAction("/api/admin/deleteAnnouncement",params)
export const adminUnuseFood=(params)=>postAction("/api/admin/food/unuse",params)
export const adminInuseFood=(params)=>postAction("/api/admin/food/use",params)
export const adminEditFood=(data)=>postAction("/api/admin/food/edit",null,data)
export const adminAddFood=(data)=>postAction("/api/admin/food/add",null,data)
export const adminAddAlert=(data)=>postAction("/api/admin/announcement/add",null,data)
export const adminGetOrders=(params)=>getAction("/api/admin/finishedOrder",params)
export const adminGetOrderDetail=(params)=>getAction("/api/admin/finishedOrder/detail",params)
export const adminGetCustomer=(params)=>getAction("/api/admin/customer",params)
export const adminGetEmployee=(params)=>getAction("/api/admin/employee",params)
export const adminDeleteEmployee=(params)=>deleteAction("/api/admin/deleteEmployee",params)
export const adminAddEmployee=(data)=>postAction("/api/admin/addEmployee",null,data)
export const adminEditEmployee=(data)=>postAction("/api/admin/editEmployee",null,data)
export const adminGetWishRank=(params)=>getAction("/api/admin/top/wishList",params)
export const adminGetWeek=(params)=>getAction("/api/admin/sale/week",params)
export const adminGetMonth=(params)=>getAction("/api/admin/sale/month",params)
export const adminGetYear=(params)=>getAction("/api/admin/sale/year",params)
export const adminGetVip=(params)=>getAction("/api/admin/vip",params)
export const adminGetHotDish=(params)=>getAction("/api/admin/hot",params)
export const adminGetLackDish=(params)=>getAction("/api/admin/urgent",params)
export const adminGetHotPot=(params)=>getAction("/api/admin/hotMap",params)